version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: GreenGameDB
      POSTGRES_USER: GreenGame
      POSTGRES_PASSWORD: GreenGamePassword
    ports:
      - 42069:5432
    volumes:
      - GGdata:/var/lib/GreenGame/data
volumes:
  GGdata:
